import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

import { NuqsAdapter } from 'nuqs/adapters/next/app'
import Script from "next/script";


const dmSans = DM_Sans({
  subsets: ["latin"],
})

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Trade Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased`}
      >
        <Script 
          strategy="beforeInteractive"
          src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}/>
        <NuqsAdapter>
          <TRPCReactProvider>
            {children}
            <Toaster/>
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
